// <auto-generated />
using System;
using CustomCADSolutions.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomCADSolutions.AppWithIdentity.Data.Migrations
{
    [DbContext(typeof(CadContext))]
    [Migration("20240206000206_FixedCategoryEnumerationAgain")]
    partial class FixedCategoryEnumerationAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomCADSolutions.Infrastructure.Data.Models.Cad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identification of 3D Model");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasComment("Category of 3D Model");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("CreationDate of 3D Model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of 3D Model");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Url of 3D Model");

                    b.HasKey("Id");

                    b.ToTable("Cads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Name = "Toothless",
                            Url = "46fe9e9caf84495baa4d528bb33b1b34"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Name = "Baby Yoda",
                            Url = "0950c0ef766b4d93babd3a0f0cd4ed0e"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Name = "Son Goku",
                            Url = "bb96bd63cc90439daa7fd37ee5daa881"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Name = "MK Mobile Klassic Smoke",
                            Url = "d91a0437d3a74a7e8a3d9f8c1162bfc3"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Name = "Daft Punk",
                            Url = "4e1dfa109e8b40a9abb7bbdb0b105e7a"
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Name = "Verne",
                            Url = "5178e98aaa6a4d9d9db7a0d86b52b40c"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Name = "Bodybuilder Doge",
                            Url = "c9e0581f7d2d4882b7f47aec5199325c"
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Name = "Superman",
                            Url = "2c65245c84d04ff8835c165c728bbd53"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Name = "Chica",
                            Url = "2f5d647986ed44058b0c16c061998739"
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Name = "Minecraft skin",
                            Url = "fa967cc9d829475b8c8f830b416842ef"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Name = "Butterfly",
                            Url = "d45ea22770f44818949e8933b853c6c4"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Name = "Jellyfish",
                            Url = "81be051e683646d3922b2f6e71eafa11"
                        },
                        new
                        {
                            Id = 13,
                            Category = 1,
                            Name = "Horse",
                            Url = "15e0faf8e6c44dfea3f462d0ea2de2a2"
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            Name = "Chameleon",
                            Url = "7b02c861d6384fb58ac14fcd54d98475"
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            Name = "T-rex",
                            Url = "e18c433cdd1c49f8ac152348b7384037"
                        },
                        new
                        {
                            Id = 16,
                            Category = 2,
                            Name = "Rhino",
                            Url = "8e97b62a90f44ce19ea9e3fd421f55b4"
                        },
                        new
                        {
                            Id = 17,
                            Category = 2,
                            Name = "Shark",
                            Url = "9fcd3e15d0494428b4466cac33587009"
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            Name = "Crab",
                            Url = "a222d47f0465494193f71943bb7048b6"
                        },
                        new
                        {
                            Id = 19,
                            Category = 2,
                            Name = "Blobfish",
                            Url = "a0e3375984274cf8b7cdc5a933c0629a"
                        },
                        new
                        {
                            Id = 20,
                            Category = 2,
                            Name = "Turtle",
                            Url = "98642490cc824df6b6101c85685cd0fe"
                        },
                        new
                        {
                            Id = 21,
                            Category = 2,
                            Name = "Korean Dragon",
                            Url = "a2b3bc23d51f46ba9b6108348f0c1098"
                        },
                        new
                        {
                            Id = 22,
                            Category = 2,
                            Name = "Meji man smoking",
                            Url = "c03779126db440a4a2067dd8b2f2fa1c"
                        },
                        new
                        {
                            Id = 23,
                            Category = 2,
                            Name = "Cute Mushroom",
                            Url = "ffc370ddc6d542d590b9f503d0892ce0"
                        },
                        new
                        {
                            Id = 24,
                            Category = 2,
                            Name = "Indian God",
                            Url = "5a696c0af274432cb91b6640f50f1e2c"
                        },
                        new
                        {
                            Id = 25,
                            Category = 2,
                            Name = "One Piece Ship",
                            Url = "fbb3018c6ed64f36b482beaf12a9598f"
                        },
                        new
                        {
                            Id = 26,
                            Category = 2,
                            Name = "Parking lot",
                            Url = "28dd1cc6c5a84140aa93fe315ca0e344"
                        },
                        new
                        {
                            Id = 27,
                            Category = 2,
                            Name = "ARC-170 Starfighter",
                            Url = "06c7a3a6139249b4ae0a180ff9d82fe2"
                        },
                        new
                        {
                            Id = 28,
                            Category = 2,
                            Name = "Aladin Forbidden Treasure",
                            Url = "b6b2b65fd7ae4424a73fde3eccb40558"
                        },
                        new
                        {
                            Id = 29,
                            Category = 2,
                            Name = "Witcher Sword",
                            Url = "a14077a1620c43b7ae08ba1f7e5f9874"
                        },
                        new
                        {
                            Id = 30,
                            Category = 2,
                            Name = "Robots",
                            Url = "1300eb8e684b42868bda89657cac1605"
                        },
                        new
                        {
                            Id = 31,
                            Category = 3,
                            Name = "Chinese Old Wall Building",
                            Url = "70fda0cf110c4ccbb7de300560fc35a7"
                        },
                        new
                        {
                            Id = 32,
                            Category = 3,
                            Name = "Old Chinese Roof House",
                            Url = "7d039b0a0db148cf919895668acea0f7"
                        },
                        new
                        {
                            Id = 33,
                            Category = 3,
                            Name = "DAE Diroma Rustborn",
                            Url = "fb5b57f347064e73a494ecc52bc05498"
                        },
                        new
                        {
                            Id = 34,
                            Category = 3,
                            Name = "Catholic Church",
                            Url = "3c17b4155d7f40448f528cbbb5f14910"
                        },
                        new
                        {
                            Id = 35,
                            Category = 3,
                            Name = "Windmill",
                            Url = "e9667197a82d4ea49319e89bdea87005"
                        },
                        new
                        {
                            Id = 36,
                            Category = 3,
                            Name = "Old Japanese Temple",
                            Url = "b58ace5581fd41c4adc0bf482b4eef35"
                        },
                        new
                        {
                            Id = 37,
                            Category = 3,
                            Name = "Temple Environment",
                            Url = "b48e325111414dc087001aba3b84632a"
                        },
                        new
                        {
                            Id = 38,
                            Category = 3,
                            Name = "Grandma's House",
                            Url = "edae469d3d674f7b885f8f8c523f0461"
                        },
                        new
                        {
                            Id = 39,
                            Category = 3,
                            Name = "G-Toilet 4.0 V3",
                            Url = "c7342e31cb3f4347aa1e529e42016a02"
                        },
                        new
                        {
                            Id = 40,
                            Category = 3,
                            Name = "Temple",
                            Url = "6cee019036f748b888d035e010a24bf2"
                        },
                        new
                        {
                            Id = 41,
                            Category = 3,
                            Name = "Mermaid",
                            Url = "f29e201673ec46ebba5c91cabee8a9f8"
                        },
                        new
                        {
                            Id = 42,
                            Category = 3,
                            Name = "Demon Mask",
                            Url = "8f25337b683d415e8f393eff60bc2aa1"
                        },
                        new
                        {
                            Id = 43,
                            Category = 3,
                            Name = "Gun",
                            Url = "1fb17a68da1543899ef4ed042d334384"
                        },
                        new
                        {
                            Id = 44,
                            Category = 3,
                            Name = "Biomechanical whale",
                            Url = "daaaf76c7d9e45618b5da7bf8f08e034"
                        },
                        new
                        {
                            Id = 45,
                            Category = 3,
                            Name = "Wish-granting dragon",
                            Url = "35d9c60b0fdf440a9ee44f9481b3173e"
                        },
                        new
                        {
                            Id = 46,
                            Category = 4,
                            Name = "Pokemon",
                            Url = "d1eac757cd234d85b8f010252f740417"
                        },
                        new
                        {
                            Id = 47,
                            Category = 4,
                            Name = "Angel of Death",
                            Url = "9755efc92e2847e198d28852393bfe5e"
                        },
                        new
                        {
                            Id = 48,
                            Category = 4,
                            Name = "Neytiri",
                            Url = "ef501601f20c4a759a804a86c70e2cbb"
                        },
                        new
                        {
                            Id = 49,
                            Category = 4,
                            Name = "Witcher Sword",
                            Url = "a14077a1620c43b7ae08ba1f7e5f9874"
                        },
                        new
                        {
                            Id = 50,
                            Category = 4,
                            Name = "Mystic Abyss Whale",
                            Url = "6c2067c38e324e03a5a4a5cbc8022c2c"
                        },
                        new
                        {
                            Id = 51,
                            Category = 4,
                            Name = "Purple Down Coat",
                            Url = "482f2f6b0724424093a958cbcb65ca2c"
                        },
                        new
                        {
                            Id = 52,
                            Category = 4,
                            Name = "Stripped Fedora Hat",
                            Url = "3d0638441bf9415ca9800ef498299895"
                        },
                        new
                        {
                            Id = 53,
                            Category = 4,
                            Name = "Sunglasses",
                            Url = "3b31fcf2f9e54b9ca86e0e29ca86d3fb"
                        },
                        new
                        {
                            Id = 54,
                            Category = 4,
                            Name = "Pikachu hoodie",
                            Url = "026fd91fc38d47c2b2f27ecdd1d8fb69"
                        },
                        new
                        {
                            Id = 55,
                            Category = 4,
                            Name = "Dragon New Year Dress",
                            Url = "52a260fd27dd4d24beab51cffb6da0f9"
                        },
                        new
                        {
                            Id = 56,
                            Category = 4,
                            Name = "Purple Senate Gown",
                            Url = "8aa82542e714477b85e46ae958ad8fa9"
                        },
                        new
                        {
                            Id = 57,
                            Category = 4,
                            Name = "White shirt black leather skirt outfit",
                            Url = "9f9e3d05217a4f969cd08224ad0b0aee"
                        },
                        new
                        {
                            Id = 58,
                            Category = 4,
                            Name = "Green and white hoodie",
                            Url = "af100701826e4bb9abc1ff1a1d24ab1e"
                        },
                        new
                        {
                            Id = 59,
                            Category = 4,
                            Name = "School Uniform",
                            Url = "887e3a1705f040bc91597e1fad47a7c0"
                        },
                        new
                        {
                            Id = 60,
                            Category = 4,
                            Name = "Roman style outfits",
                            Url = "629f5466d75f42a4abd377a951b5574e"
                        },
                        new
                        {
                            Id = 61,
                            Category = 5,
                            Name = "Forest",
                            Url = "15e0faf8e6c44dfea3f462d0ea2de2a2"
                        },
                        new
                        {
                            Id = 62,
                            Category = 5,
                            Name = "Ocean wave",
                            Url = "f86f444dc7cc4458a0140f05a03c5896"
                        },
                        new
                        {
                            Id = 63,
                            Category = 5,
                            Name = "Mountain",
                            Url = "aa0ce50cda2847e3b417c2d48253a1e5"
                        },
                        new
                        {
                            Id = 64,
                            Category = 5,
                            Name = "Hanging pots",
                            Url = "f7dc21a8f90f49069295f2d6aa1b1334"
                        },
                        new
                        {
                            Id = 65,
                            Category = 5,
                            Name = "Plants",
                            Url = "e515bae7a87740f1b8cc6bdc5b9821fa"
                        },
                        new
                        {
                            Id = 66,
                            Category = 5,
                            Name = "Trees",
                            Url = "e38c9ccc28994580b27bc50871bed80f"
                        },
                        new
                        {
                            Id = 67,
                            Category = 5,
                            Name = "Water Lily",
                            Url = "70041f31b7224d73800ee0e485757a08"
                        },
                        new
                        {
                            Id = 68,
                            Category = 5,
                            Name = "Earth's Core",
                            Url = "44c547c28fbf46f4ab430bf1398f5fdb"
                        },
                        new
                        {
                            Id = 69,
                            Category = 5,
                            Name = "Fern Forest",
                            Url = "e3fb505d5f6d47118da83ebacf92929c"
                        },
                        new
                        {
                            Id = 70,
                            Category = 5,
                            Name = "Mushrooms",
                            Url = "27dc43f90c5f463d91a762e4d1d099e5"
                        },
                        new
                        {
                            Id = 71,
                            Category = 5,
                            Name = "Drone",
                            Url = "cfef32de2c704b758a0d80166f664302"
                        },
                        new
                        {
                            Id = 72,
                            Category = 5,
                            Name = "iPhone 15 Pro",
                            Url = "18c0acd4c8a04a50ada94b99b1ed8a2c"
                        },
                        new
                        {
                            Id = 73,
                            Category = 5,
                            Name = "USB",
                            Url = "3682b098a3df42c188ddde947d674740"
                        },
                        new
                        {
                            Id = 74,
                            Category = 5,
                            Name = "iPad",
                            Url = "7af563e18e5145deb46d85c33afe6ce0"
                        },
                        new
                        {
                            Id = 75,
                            Category = 5,
                            Name = "Batteries",
                            Url = "eefe894897f746f689b899f80b15d325"
                        },
                        new
                        {
                            Id = 76,
                            Category = 6,
                            Name = "PS5",
                            Url = "54810f0b23a441ca93f44a8b06ec937b"
                        },
                        new
                        {
                            Id = 77,
                            Category = 6,
                            Name = "Casio Watch",
                            Url = "e8e86c83768e40d2b2349355d6f2ed25"
                        },
                        new
                        {
                            Id = 78,
                            Category = 6,
                            Name = "Camera",
                            Url = "d2e75e8571dc496f80db1965beb6467d"
                        },
                        new
                        {
                            Id = 79,
                            Category = 6,
                            Name = "Tape recorder",
                            Url = "5ea4230620e44cad93d72df5a098425a"
                        },
                        new
                        {
                            Id = 80,
                            Category = 6,
                            Name = "Bulb",
                            Url = "4c064f93de0c46b981a92c94d629c64d"
                        },
                        new
                        {
                            Id = 81,
                            Category = 6,
                            Name = "Old Police Car",
                            Url = "011bdbb31ba641aa9c9912df4ce1ff99"
                        },
                        new
                        {
                            Id = 82,
                            Category = 6,
                            Name = "Cybertruck",
                            Url = "5a86defda4b24836a504fe5e597fdb17"
                        },
                        new
                        {
                            Id = 83,
                            Category = 6,
                            Name = "School Bus",
                            Url = "f18faa73da8c4ee3a19e8db1d4ae4cd9"
                        },
                        new
                        {
                            Id = 84,
                            Category = 6,
                            Name = "Nissan 200SX S13",
                            Url = "151053ad7e0a4fcf944a7b523722dad6"
                        },
                        new
                        {
                            Id = 85,
                            Category = 6,
                            Name = "Futuristic ZAZ Zaporozhec",
                            Url = "a0910debd9364cc1b8a698d2862e2f99"
                        },
                        new
                        {
                            Id = 86,
                            Category = 6,
                            Name = "Mercedes",
                            Url = "18b16cf5c8574f8f93c5b04b3b945ef1"
                        },
                        new
                        {
                            Id = 87,
                            Category = 6,
                            Name = "Russian motorcycle",
                            Url = "d5d366471b4c4d4c9365d52b5c963c13"
                        },
                        new
                        {
                            Id = 88,
                            Category = 6,
                            Name = "F-35C Lightning II",
                            Url = "1b187b18ce1541e2ae3321065ac61cbe"
                        },
                        new
                        {
                            Id = 89,
                            Category = 6,
                            Name = "Herbe",
                            Url = "beac1b607f2544708891b2491886e87f"
                        },
                        new
                        {
                            Id = 90,
                            Category = 6,
                            Name = "Tesla Model X",
                            Url = "36e9d3598c554bb69f3d9cd00e161818"
                        },
                        new
                        {
                            Id = 91,
                            Category = 7,
                            Name = "Chroma Squares",
                            Url = "31967e23bce548a19f3b6acf0be42747"
                        },
                        new
                        {
                            Id = 92,
                            Category = 7,
                            Name = "Vector Prism",
                            Url = "913759bdac3b4084b46ddf3b40d12f82"
                        },
                        new
                        {
                            Id = 93,
                            Category = 7,
                            Name = "Rigged Torus",
                            Url = "4e5d1d892c0e4d468f254ec3d0707bd4"
                        },
                        new
                        {
                            Id = 94,
                            Category = 7,
                            Name = "Aurora Somnium",
                            Url = "dc45cd579572424d8793b3c7241618c3"
                        },
                        new
                        {
                            Id = 95,
                            Category = 7,
                            Name = "Core Rotation",
                            Url = "42ed6690184249f3b8343204406729f4"
                        },
                        new
                        {
                            Id = 96,
                            Category = 7,
                            Name = "Inner Reflection",
                            Url = "1dd1dac603634aa3b5f150ac91471866"
                        },
                        new
                        {
                            Id = 97,
                            Category = 7,
                            Name = "The Call",
                            Url = "e92d198bc95c4fb7929b2605c919ad3d"
                        },
                        new
                        {
                            Id = 98,
                            Category = 7,
                            Name = "Spheres and Torus",
                            Url = "8b94ad7d325f420fa5b71ae6b550f03c"
                        },
                        new
                        {
                            Id = 99,
                            Category = 7,
                            Name = "Cradled by the void",
                            Url = "36a66e98adad4daf8d434d96bfbcb762"
                        },
                        new
                        {
                            Id = 100,
                            Category = 7,
                            Name = "Tentakulum",
                            Url = "dd0dd9f4fb35422e9dd15c2a443dcd39"
                        },
                        new
                        {
                            Id = 101,
                            Category = 7,
                            Name = "Muscular Male",
                            Url = "c1b72483e097443fbf0a94ddac01251f"
                        },
                        new
                        {
                            Id = 102,
                            Category = 7,
                            Name = "Circular System",
                            Url = "e7abdabd3a6d422cb25e6e63b45b1ab0"
                        },
                        new
                        {
                            Id = 103,
                            Category = 7,
                            Name = "Digestive System",
                            Url = "758773af9d6c4368a5549bef536484a9"
                        },
                        new
                        {
                            Id = 104,
                            Category = 7,
                            Name = "Muscle system",
                            Url = "7ea21567ff9942bf9511e2d99efe85d9"
                        },
                        new
                        {
                            Id = 105,
                            Category = 7,
                            Name = "Mouth",
                            Url = "d92cfd5873ac43299c7b64cdf9725526"
                        },
                        new
                        {
                            Id = 106,
                            Category = 8,
                            Name = "Heart",
                            Url = "775d6629622740de8a5ed61a959c7506"
                        },
                        new
                        {
                            Id = 107,
                            Category = 8,
                            Name = "Eye",
                            Url = "6adbd6538cd146d484c9ad950be69aa5"
                        },
                        new
                        {
                            Id = 108,
                            Category = 8,
                            Name = "Skull",
                            Url = "2d6feb90e20d4389afb2b885eece0a48"
                        },
                        new
                        {
                            Id = 109,
                            Category = 8,
                            Name = "Ear",
                            Url = "4f5438fc9337454587ec4a2c30c8c42f"
                        },
                        new
                        {
                            Id = 110,
                            Category = 8,
                            Name = "Blood vessels",
                            Url = "c26e0f2e75fe4087aa8c4ecee2cad1aa"
                        },
                        new
                        {
                            Id = 111,
                            Category = 8,
                            Name = "Hot Dog",
                            Url = "7d32ac170c274d08b29993bb61192fe2"
                        },
                        new
                        {
                            Id = 112,
                            Category = 8,
                            Name = "Donut",
                            Url = "7f0b1caa6f7e448d9ce33cad8b255c2b"
                        },
                        new
                        {
                            Id = 113,
                            Category = 8,
                            Name = "Milka Chocolate",
                            Url = "4455647163644960b4851ccd357089c1"
                        },
                        new
                        {
                            Id = 114,
                            Category = 8,
                            Name = "Chicken Wing",
                            Url = "7cc9b52f39c44e2098fe7d4cf2d25725"
                        },
                        new
                        {
                            Id = 115,
                            Category = 8,
                            Name = "Cake",
                            Url = "d8b2c2cc92914fefa0aac855fc434e02"
                        },
                        new
                        {
                            Id = 116,
                            Category = 8,
                            Name = "Chips",
                            Url = "2342efc8c65a431db89747964e96f929"
                        },
                        new
                        {
                            Id = 117,
                            Category = 8,
                            Name = "Waffles",
                            Url = "37e628439c5a47c4aed209c76b442960"
                        },
                        new
                        {
                            Id = 118,
                            Category = 8,
                            Name = "Burger",
                            Url = "346ebe0033ba48f7bc2e10d44a5b482f"
                        },
                        new
                        {
                            Id = 119,
                            Category = 8,
                            Name = "Muffins",
                            Url = "307dc81f3890494487ff2c7a12a2afb8"
                        },
                        new
                        {
                            Id = 120,
                            Category = 8,
                            Name = "Lollipop",
                            Url = "3071e2c6382842509b17f2535224444d"
                        },
                        new
                        {
                            Id = 121,
                            Category = 9,
                            Name = "Table with chairs",
                            Url = "8f2f097e2eda40c691956ad8de31ae8b"
                        },
                        new
                        {
                            Id = 122,
                            Category = 9,
                            Name = "Knife",
                            Url = "2be56aac48d042449a89cf5c74aae4bf"
                        },
                        new
                        {
                            Id = 123,
                            Category = 9,
                            Name = "Desk",
                            Url = "7d42419d4a034786b04374cd313ffb64"
                        },
                        new
                        {
                            Id = 124,
                            Category = 9,
                            Name = "Couches",
                            Url = "b87c52f6f86642dc8c7bc8e321ac3a7b"
                        },
                        new
                        {
                            Id = 125,
                            Category = 9,
                            Name = "Clock",
                            Url = "73ee073c9c0e4f82ac5e4357b18a220a"
                        },
                        new
                        {
                            Id = 126,
                            Category = 9,
                            Name = "Carpentary tools",
                            Url = "b910747a856b40d1b85f1cfb1123ce4f"
                        },
                        new
                        {
                            Id = 127,
                            Category = 9,
                            Name = "Candle holder",
                            Url = "2238c4e2fd2945a89b69d26b3a362b2f"
                        },
                        new
                        {
                            Id = 128,
                            Category = 9,
                            Name = "Bookshelf",
                            Url = "dd9df1268f954a18b248a6d321aadab5"
                        },
                        new
                        {
                            Id = 129,
                            Category = 9,
                            Name = "Household items",
                            Url = "31c376a493914f5d90f1e2894bd33399"
                        },
                        new
                        {
                            Id = 130,
                            Category = 9,
                            Name = "Viking war horn",
                            Url = "82a543e0ddc74156b4ded2297cfa41d0"
                        },
                        new
                        {
                            Id = 131,
                            Category = 9,
                            Name = "Gym Machines",
                            Url = "0582bd07f01b49b09b3552553c3467b8"
                        },
                        new
                        {
                            Id = 132,
                            Category = 9,
                            Name = "Ping Pong",
                            Url = "8e47acdad1824af79e0ee17267cf219b"
                        },
                        new
                        {
                            Id = 133,
                            Category = 9,
                            Name = "Dumbell",
                            Url = "e4fb3a53b8f64103b223a73877e2e76c"
                        },
                        new
                        {
                            Id = 134,
                            Category = 9,
                            Name = "Billiard",
                            Url = "8942a97e5b034d6595ae8861a9b17090"
                        },
                        new
                        {
                            Id = 135,
                            Category = 9,
                            Name = "Barbell",
                            Url = "45aa468ba3ff4e1cb6f3fa6022f62c2c"
                        },
                        new
                        {
                            Id = 136,
                            Category = 10,
                            Name = "Balls",
                            Url = "a1ca652635c64fbeab407afaab798f50"
                        },
                        new
                        {
                            Id = 137,
                            Category = 10,
                            Name = "Boxing gloves",
                            Url = "4c0fc8ab91c74b73a8ffc58b8dc0cacd"
                        },
                        new
                        {
                            Id = 138,
                            Category = 10,
                            Name = "Azteca Mexico Football",
                            Url = "880bcabd62544bf3ab5246af0721ddc8"
                        },
                        new
                        {
                            Id = 139,
                            Category = 10,
                            Name = "Boxing bag",
                            Url = "5e61a526b82149d4a536ccd0208677a0"
                        },
                        new
                        {
                            Id = 140,
                            Category = 10,
                            Name = "Tennis Rackets",
                            Url = "1589dccdc3cf4ff5af17fe975b33650e"
                        });
                });

            modelBuilder.Entity("CustomCADSolutions.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identification of Order");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Identification of User");

                    b.Property<int>("CadId")
                        .HasColumnType("int")
                        .HasComment("Identification of 3D model");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Description of Order");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of Order");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CadId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CustomCADSolutions.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomCADSolutions.Infrastructure.Data.Models.Cad", "Cad")
                        .WithOne("Order")
                        .HasForeignKey("CustomCADSolutions.Infrastructure.Data.Models.Order", "CadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Cad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomCADSolutions.Infrastructure.Data.Models.Cad", b =>
                {
                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
